// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYRCN3LgtV9xGYgXo85S7Xzo11khII_6w',
    appId: '1:713424803842:web:cc34b102462580a42eaf1b',
    messagingSenderId: '713424803842',
    projectId: 'flutter-ejemplo-1bdc4',
    authDomain: 'flutter-ejemplo-1bdc4.firebaseapp.com',
    storageBucket: 'flutter-ejemplo-1bdc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUpN2XT7ZzIT1mIc3P79FEmBSzg7fvAGg',
    appId: '1:713424803842:android:30bf29604146b69d2eaf1b',
    messagingSenderId: '713424803842',
    projectId: 'flutter-ejemplo-1bdc4',
    storageBucket: 'flutter-ejemplo-1bdc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx7PE1x4oGF9_pFhA-nXEbkU8eayr4H2c',
    appId: '1:713424803842:ios:20f562af506f63e52eaf1b',
    messagingSenderId: '713424803842',
    projectId: 'flutter-ejemplo-1bdc4',
    storageBucket: 'flutter-ejemplo-1bdc4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx7PE1x4oGF9_pFhA-nXEbkU8eayr4H2c',
    appId: '1:713424803842:ios:20f562af506f63e52eaf1b',
    messagingSenderId: '713424803842',
    projectId: 'flutter-ejemplo-1bdc4',
    storageBucket: 'flutter-ejemplo-1bdc4.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
